# Generated by Django 3.1.3 on 2020-12-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_class_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_days',
            field=models.CharField(choices=[('sat', 'sat'), ('san', 'san'), ('mon', 'mon'), ('tue', 'tue'), ('wed', 'wed'), ('thr', 'thr'), ('fir', 'fri')], max_length=50),
        ),
    ]
