# Generated by Django 3.1.3 on 2020-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201202_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_days',
            field=models.CharField(choices=[('st', 'st'), ('mw', 'mw'), ('ra', 'ra')], max_length=50),
        ),
    ]
