///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EnrolledUserModel {
/*
{
  "id": 2,
  "url": "http://192.168.0.108:8000/api/users/users/2/",
  "username": "1812966642",
  "email": "shakil.hossain3@northsouth.edu",
  "is_staff": false,
  "is_superuser": false
} 
*/

  int? id;
  String? url;
  String? username;
  String? email;
  bool? isStaff;
  bool? isSuperuser;

  EnrolledUserModel({
    this.id,
    this.url,
    this.username,
    this.email,
    this.isStaff,
    this.isSuperuser,
  });
  EnrolledUserModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    url = json["url"]?.toString();
    username = json["username"]?.toString();
    email = json["email"]?.toString();
    isStaff = json["is_staff"];
    isSuperuser = json["is_superuser"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["url"] = url;
    data["username"] = username;
    data["email"] = email;
    data["is_staff"] = isStaff;
    data["is_superuser"] = isSuperuser;
    return data;
  }
}
