# Generated by Django 3.1.3 on 2021-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201211_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='due',
        ),
        migrations.AddField(
            model_name='post',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
    ]
